pipeline {
	agent any
	options {
		skipDefaultCheckout()
	}
    environment {
        AUTOMATION_GIT_BRANCH = 'jenkins_pipeline'
    }
    parameters {
        choice(name: 'ENV_DIRECTORY', choices:  'stg\nstg-dev\nstg-load\nstg-qa', description: 'configuration directory')

        booleanParam(defaultValue: true, name: 'CHECKOUT')
        booleanParam(defaultValue: true, name: 'BUILD')
        booleanParam(defaultValue: true, name: 'DOCKER_BUILD')
        booleanParam(defaultValue: true, name: 'PUSH')
        booleanParam(defaultValue: true, name: 'DEPLOY')
        booleanParam(defaultValue: true, name: 'SWITCH')
        string(name: "EUREKA_SERVER_GIT_BRANCH", description: 'passed from prior "poll" job like:<br>"origin/feature/&lt;branch name&gt;" or<br>"refs/tags/&lt;tag name&gt;"', defaultValue: 'develop')
    }
    stages {
        stage('Preparation') {
            steps {
                echo "[PREPARATION] START"
                script {
					eurekaServerGitUrl = 'https://github.com/masudbappy/eureka-server.git'
                  	eurekaServerBaseDir = 'api_base_dir'
                    automationGitUrl = 'https://github.com/masudbappy/2023-automation.git'
                    automationBranch = env.AUTOMATION_GIT_BRANCH
                    automationDir = 'automation_dir'
                    configDir = automationDir + '/05_MobileAppAPIs/0503_ConfigServer/050302_SpringCloudConfigServer/appConfig'

                    }
                echo "[PREPARATION] END"
            }
        }
        stage('Checkout') {
            when { expression { return params.CHECKOUT } }
            steps {
                echo "[CHECKOUT] START"
                checkout scmGit(
                    branches: [[name: automationBranch]],
                    extensions: [],
                    userRemoteConfigs: [[url: automationGitUrl]]
                    )
                echo ".......automation project end .............."
                checkout scmGit(
                    branches: [[name: params.EUREKA_SERVER_GIT_BRANCH]],
                    extensions: [],
                    userRemoteConfigs: [[url: eurekaServerGitUrl]]
                    )
                echo ".......eureka git checkout end .............."

                echo "[CHECKOUT] END"
            }
        }
        stage('Build') {
            steps {
                echo "[BUILD] START"

                echo "[BUILD] END"
            }
        }
        stage('Docker build'){
            when { expression { return params.DOCKER_BUILD } }
            steps {
                echo "[Docker build] START"

                echo "[Docker build] END"
            }
        }
        stage('Docker push'){
            when { expression { return params.PUSH } }
            steps {
                echo "[Docker push] START"

                echo "[Docker push] END"
            }
        }
        stage('Deploy and switch preparation') {
            when { expression { return params.DEPLOY } }
            steps {
                echo "[Deploy and switch preparation] START"

                echo "[Deploy and switch preparation] END"
            }
        }
        stage('Deploy') {
            when { expression { return params.DEPLOY } }
            steps {
                echo "[DEPLOY] START"
                echo "[DEPLOY] END"
            }
        }
        stage('Switch') {
            when { expression { return params.SWITCH } }
            steps {
                echo "[SWITCH] START"
            }
        }
    }
    post {
        always {
            deleteDir()
        }
    }
}
